"""Nested model-comparison ladder for the belief-state RL model.

Does each learning component earn its place?  We fit the full two-timescale
actor-critic and a sequence of *nested* reduced models — each switching off one
learning channel by pinning its learning rate to the lower bound — and compare
their **held-out** predictive log-likelihood.  A component earns its place if
removing it lowers held-out likelihood.

    full               critic (eta_w) + lick/velocity actors (eta_a) both learn
    no_value_learning  eta_w off  -> critic frozen at the flat w_init
    no_actors          eta_a off  -> lick/velocity are pure critic read-outs
                                     (no learned spatial control — the redesign's
                                     core addition)
    fixed_agent        eta_w & eta_a off -> nothing learns (the floor)

Held-out evaluation uses the **forward / blocked** split (the last FORWARD_FRAC
of trials), so the comparison tests learning-curve generalisation — exactly the
behaviour the slow channels exist to produce.  Learning is teacher-forced through
all trials (learn_mask full); only the likelihood is restricted to the held-out
block.

Runs on the real task mice by default; set RLMODEL_LADDER_SYNTH=1 to run a small
synthetic demonstration (data generated by the full model, so the full model
should win) that needs no .mat file.

Incremental: each invocation fits a few (mouse, model) cells within a time
budget; the last invocation writes the summary + figure.  Run repeatedly:

    python -m scripts.run_model_ladder                       # real data
    RLMODEL_LADDER_SYNTH=1 python -m scripts.run_model_ladder  # synthetic demo
"""
from __future__ import annotations

import os
import sys
import time

import numpy as np
import jax.numpy as jnp
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from rl_model.config import TaskConfig                       # noqa: E402
from rl_model.agent import session_latents                   # noqa: E402
from rl_model.fitting import fit_mouse, _BOUND                # noqa: E402
from rl_model.synthetic import make_cohort                    # noqa: E402
from rl_model.io_real import load_real_cohort                 # noqa: E402

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESDIR = os.path.join(HERE, "results")
FIGDIR = os.path.join(HERE, "figures")
MAT = os.path.join(HERE, "..", "processed_data", "preprocessed_data5cm.mat")

SYNTH = os.environ.get("RLMODEL_LADDER_SYNTH", "0") == "1"
LADDERDIR = os.path.join(RESDIR, "ladder_synth" if SYNTH else "ladder_real")
os.makedirs(LADDERDIR, exist_ok=True)
os.makedirs(FIGDIR, exist_ok=True)

FORWARD_FRAC = 0.25
# Seconds of fitting per invocation.  Small default keeps each run inside a cloud
# shell timeout (re-run until DONE); set RLMODEL_TIME_BUDGET to a large number to
# do every (mouse, model) cell in one command on a local machine.
TIME_BUDGET = float(os.environ.get("RLMODEL_TIME_BUDGET", "800" if SYNTH else "30"))
OFF = -_BOUND                       # unconstrained value that switches a rate off

# name -> learning rates pinned off
LADDER = {
    "full": [],
    "no_value_learning": ["eta_w"],
    "no_actors": ["eta_a"],
    "fixed_agent": ["eta_w", "eta_a"],
}
ORDER = list(LADDER)


def log(m):
    print(f"[{time.strftime('%H:%M:%S')}] {m}", flush=True)


def get_cohort(cfg):
    if SYNTH:
        coh = make_cohort(n_mice=3, n_trials=120, seed=2027, jitter=0.3, cfg=cfg)
        out = []
        for m in range(coh["licks"].shape[0]):
            licks = coh["licks"][m]
            out.append(dict(mouse=f"S{m:02d}", licks=licks, logv=coh["logv"][m],
                            mask=np.ones_like(licks, float), n_trials=licks.shape[0]))
        return out
    return load_real_cohort(MAT, cfg)


def forward_split(nt):
    cut = max(int(round(nt * (1.0 - FORWARD_FRAC))), 1)
    test = np.arange(cut, nt)
    train = np.arange(0, cut)
    return train, test


def per_bin(ll, mask, idx):
    return float(ll[idx].sum() / max(mask[idx].sum(), 1.0))


def fit_cell(mouse, model, cfg):
    """Fit one (mouse, model) cell; return held-out LL/bin (lick, vel, total)."""
    nt = mouse["n_trials"]
    licks, logv, mask = (np.asarray(mouse["licks"], float),
                         np.asarray(mouse["logv"], float),
                         np.asarray(mouse["mask"], float))
    train, test = forward_split(nt)
    score = mask.copy()
    score[test, :] = 0.0                          # held-out block out of the objective
    learn = mask                                  # learning still runs through all trials

    fixed = {name: OFF for name in LADDER[model]}
    mi = 150 if SYNTH else (250 if nt > 200 else 400)
    res = fit_mouse(licks, logv, mask=score, learn_mask=learn, cfg=cfg,
                    n_restarts=1, seed=hash(mouse["mouse"]) % 10_000,
                    maxiter=mi, fixed=fixed)
    lat = session_latents(jnp.asarray(res["u_fit"]), licks, logv,
                          mask=mask, cfg=cfg)
    ll_lick = np.asarray(lat["loglik_lick"])
    ll_vel = np.asarray(lat["loglik_vel"])
    return dict(
        mouse=mouse["mouse"], model=model, nll=res["nll"], n_trials=nt,
        lick_test=per_bin(ll_lick, mask, test),
        vel_test=per_bin(ll_vel, mask, test),
        lick_train=per_bin(ll_lick, mask, train),
        vel_train=per_bin(ll_vel, mask, train),
    )


def cell_path(mid, model):
    return os.path.join(LADDERDIR, f"{mid}__{model}.npz")


def main():
    cfg = TaskConfig()
    cohort = get_cohort(cfg)
    log(f"{'SYNTHETIC' if SYNTH else 'REAL'} ladder — {len(cohort)} mice x {len(ORDER)} models")

    todo = [(m, model) for m in cohort for model in ORDER
            if not os.path.exists(cell_path(m["mouse"], model))]
    if todo:
        t0 = time.time()
        n = 0
        for m, model in todo:
            if time.time() - t0 > TIME_BUDGET and n > 0:
                break
            tm = time.time()
            rec = fit_cell(m, model, cfg)
            np.savez(cell_path(m["mouse"], model), **rec)
            n += 1
            log(f"  {m['mouse']:5s} {model:18s} held-out lick {rec['lick_test']:+.3f} "
                f"vel {rec['vel_test']:+.3f}  ({time.time()-tm:.1f}s)")
        remaining = sum(1 for m in cohort for md in ORDER
                        if not os.path.exists(cell_path(m["mouse"], md)))
        if remaining:
            log(f"{remaining} cells left — run again")
            return
    finalise(cohort)


def finalise(cohort):
    ids = [m["mouse"] for m in cohort]
    # held-out total (lick+vel) LL/bin per mouse x model
    tot = {model: [] for model in ORDER}
    lick = {model: [] for model in ORDER}
    for mid in ids:
        for model in ORDER:
            d = np.load(cell_path(mid, model))
            tot[model].append(float(d["lick_test"]) + float(d["vel_test"]))
            lick[model].append(float(d["lick_test"]))
    tot = {k: np.array(v) for k, v in tot.items()}
    lick = {k: np.array(v) for k, v in lick.items()}

    log("=" * 72)
    log("MODEL-COMPARISON LADDER — held-out (forward-CV) log-likelihood / bin")
    log(f"{'model':18s} {'lick LL/bin':>12s} {'total LL/bin':>13s} "
        f"{'d(full-this) total':>20s}  {'mice full>this':>15s}")
    full_tot = tot["full"]
    for model in ORDER:
        d = full_tot - tot[model]
        nbetter = int((d > 0).sum()) if model != "full" else len(full_tot)
        log(f"{model:18s} {lick[model].mean():+12.3f} {tot[model].mean():+13.3f} "
            f"{(0.0 if model=='full' else d.mean()):+20.3f}  {nbetter:6d}/{len(ids):<8d}")
    log("-" * 72)
    log("A component earns its place if d(full - reduced) > 0 (full predicts the "
        "held-out block better).")
    _figure(tot, ids)
    with open(os.path.join(RESDIR, f"DONE_ladder_{'synth' if SYNTH else 'real'}"), "w") as fh:
        fh.write("ok\n")
    log("DONE")


def _figure(tot, ids):
    fig, ax = plt.subplots(figsize=(8.5, 5))
    x = np.arange(len(ORDER))
    means = [tot[m].mean() for m in ORDER]
    sems = [tot[m].std() / np.sqrt(len(ids)) for m in ORDER]
    colors = ["#1a7a3a", "#d9a300", "#b03030", "#777777"]
    ax.bar(x, means, yerr=sems, capsize=4, color=colors[:len(ORDER)])
    # per-mouse paired lines vs full
    for j in range(len(ids)):
        ax.plot(x, [tot[m][j] for m in ORDER], c="0.6", lw=0.6, alpha=0.6, zorder=3)
    ax.set_xticks(x)
    ax.set_xticklabels(ORDER, rotation=15, ha="right")
    ax.set_ylabel("held-out total LL / bin (forward CV)")
    ax.set_title(f"Model-comparison ladder ({'synthetic' if SYNTH else 'real'} "
                 f"mice, n={len(ids)})\nhigher = better held-out prediction; "
                 "each reduced model removes one learning channel")
    fig.tight_layout()
    out = os.path.join(FIGDIR, f"fig_model_ladder_{'synth' if SYNTH else 'real'}.png")
    fig.savefig(out, dpi=140)
    plt.close(fig)
    log(f"wrote {out}")


if __name__ == "__main__":
    main()
